name: hjalpguiden
description: Mobil-först Flutter-app för myndighetstjänster
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.4.0
  
  # Routing
  go_router: ^12.0.0
  
  # TTS
  flutter_tts: ^3.8.0
  
  # Audio playback
  just_audio: ^0.9.36
  
  # Caching
  flutter_cache_manager: ^3.3.1
  
  # HTTP
  http: ^1.1.0
  
  # JSON
  json_annotation: ^4.9.0
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/content/
    - assets/audio/
